mongodb:
  host: localhost
  port: 27017
  user: test
  pass: test
  database: wine
  collection: wines
  max-id-query: '{
                 aggregate: "wines",
                 pipeline: [
                 { 
                   $group : { 
                    _id: null, 
                    max: { $max : "$id" }
                   },
                 }
                 ],
                 cursor: {}
               }'
  search-queries:
    - {
       name: findByCountry,
       exec: '{ find: "wines", filter: { country: "?1" } }',
       percentage: 15,
       params: [
                 {param1: Bulgaria},{param1: Romania},{param1: Greece},{param1: Macedonia},{param1: Turkey},{param1: Germany},{param1: France},{param1: Italy},{param1: Austria},{param1: Spain},{param1: Portugal},{param1: Argentina}
               ]
      }
    - {
       name: findByPoints,
       exec: '{ find: "wines", filter: { points: "?1" } }',
       percentage: 15,
       params: [
                 {param1: 91},{param1: 92},{param1: 93},{param1: 94},{param1: 95},{param1: 96},{param1: 97},{param1: 98},{param1: 99},{param1: 100}
               ]
      }
    - {
       name: findByPrice,
       exec: '{ find: "wines", filter: { price: ?1 } }',
       percentage: 15,
       params: [
                 {param1: 90},{param1: 91},{param1: 92},{param1: 93},{param1: 94},{param1: 95},{param1: 96},{param1: 97},{param1: 98},{param1: 99},{param1: 100},{param1: 200},{param1: 500},{param1: 1000},{param1: 2000}
               ]
      }
    - {
       name: findByCountryAndPoints,
       exec: '{ find: "wines", filter: { country: "?1", price: ?2 } }',
       percentage: 25,
       params: [
                 {param1: Bulgaria, param2: 96},{param1: Bulgaria, param2: 97},{param1: Bulgaria, param2: 98},{param1: Bulgaria, param2: 99},{param1: Bulgaria, param2: 100},
                 {param1: Romania,  param2: 96},{param1: Romania, param2: 97},{param1: Romania, param2: 98},{param1: Romania, param2: 99},{param1: Romania, param2: 100},
                 {param1: Greece, param2: 96},{param1: Greece, param2: 97},{param1: Greece, param2: 98},{param1: Greece, param2: 99},{param1: Greece, param2: 100},
                 {param1: Macedonia, param2: 96},{param1: Macedonia, param2: 97},{param1: Macedonia, param2: 98},{param1: Macedonia, param2: 99},{param1: Macedonia, param2: 100},
                 {param1: Turkey, param2: 96},{param1: Turkey, param2: 97},{param1: Turkey, param2: 98},{param1: Turkey, param2: 99},{param1: Turkey, param2: 100},
                 {param1: Germany, param2: 96},{param1: Germany, param2: 97},{param1: Germany, param2: 98},{param1: Germany, param2: 99},{param1: Germany, param2: 100},
                 {param1: France, param2: 96},{param1: France, param2: 97},{param1: France, param2: 98},{param1: France, param2: 99},{param1: France, param2: 100},
                 {param1: Italy, param2: 96},{param1: Italy, param2: 97},{param1: Italy, param2: 98},{param1: Italy, param2: 99},{param1: Italy, param2: 100},
                 {param1: Austria, param2: 96},{param1: Austria, param2: 97},{param1: Austria, param2: 98},{param1: Austria, param2: 99},{param1: Austria, param2: 100},
                 {param1: Spain, param2: 96},{param1: Spain, param2: 97},{param1: Spain, param2: 98},{param1: Spain, param2: 99},{param1: Spain, param2: 100},
                 {param1: Portugal, param2: 96},{param1: Portugal, param2: 97},{param1: Portugal, param2: 98},{param1: Portugal, param2: 99},{param1: Portugal, param2: 100},
                 {param1: Argentina, param2: 96},{param1: Argentina, param2: 97},{param1: Argentina, param2: 98},{param1: Argentina, param2: 99},{param1: Argentina, param2: 100},
                 {param1: Australia, param2: 96},{param1: Australia, param2: 97},{param1: Australia, param2: 98},{param1: Australia, param2: 99},{param1: Australia, param2: 100},
                 {param1: Chile, param2: 96},{param1: Chile, param2: 97},{param1: Chile, param2: 98},{param1: Chile, param2: 99},{param1: Chile, param2: 100},
                 {param1: Serbia, param2: 96},{param1: Serbia, param2: 97},{param1: Serbia, param2: 98},{param1: Serbia, param2: 99},{param1: Serbia, param2: 100}
               ]
      }
    - {
        name: findAggregations,
        exec: '{
                 aggregate: "wines",
                 pipeline: [
                 { 
                   $group : { 
                    _id: null, 
                     min: { $min : "$price" },
                     max: { $max : "$price" },
                     avg: { $avg : "$price" },
                     count: { $sum : 1 }
                   },
                 }
                 ],
                 cursor: {}
             }',
        percentage: 15,
        params: []
      }
    - {
        name: findAggregationsByCountry,
        exec: '{
                 aggregate: "wines",
                 pipeline: [
                 { 
                   $group : { 
                    _id: "$country", 
                     min: { $min : "$price" },
                     max: { $max : "$price" },
                     avg: { $avg : "$price" },
                     count: { $sum : 1 }
                   },
                 }
               ],
                 cursor: {}
              }',
       percentage: 15,
       params: []
      }
  update-queries: # list of com.akg.dbperfcheck.config.pojo.Query objects used for the UPDATE queries
    - {
        name: updatePointsByCountry, # name of the qiery
        exec: '{  
                 update: "wines",  
                 updates: [  
                    {  
                      q: { country: "?1" }, u: { $set: { points: 86 } }, multi: true  
                    }  
                 ],  
                 writeConcern: { w: "majority", wtimeout: 5000 }  
              }', # the actual query
        percentage: 40, # this is the percentage of executions of this query among all executed queries
        params: [
                  {param1: Bulgaria},{param1: Romania},{param1: Greece},{param1: Macedonia},{param1: Turkey},{param1: Germany},{param1: France},{param1: Italy},{param1: Austria},{param1: Spain},{param1: Portugal},{param1: Argentina}
                ] # predefined parameter values, one of them randomly will be picked up and pass to the query above
      }
    - {
        name: updatePricesByCountry,
        exec: '{  
                 update: "wines",  
                 updates: [  
                    {  
                      q: { country: "?1" }, u: { $set: { prices: 10 } }, multi: true  
                    }  
                 ],  
                 writeConcern: { w: "majority", wtimeout: 5000 }  
              }',
        percentage: 15,
        params: [
                  {param1: Bulgaria},{param1: Romania},{param1: Greece},{param1: Macedonia},{param1: Turkey},{param1: Germany},{param1: France},{param1: Italy},{param1: Austria},{param1: Spain},{param1: Portugal},{param1: Argentina}
                ]
      }
    - {
        name: updatePointsByVariety,
        exec: '{  
                 update: "wines",  
                 updates: [  
                    {  
                      q: { variety: "?1" }, u: { $set: { points: 87 } }, multi: true  
                    }  
                 ],  
                 writeConcern: { w: "majority", wtimeout: 5000 }  
              }',
        percentage: 15,
        params: [
                  {param1: Mavrud},{param1: Ruen},{param1: Cabernet Sauvignon},{param1: Red Blend},{param1: Bordeaux-style Red Blend},{param1: Sauvignon Blanc},{param1: Syrah},{param1: Riesling},{param1: Merlot},{param1: Zinfandel}
                ]
      }
    - {
        name: updatePricesByVariety,
        exec: '{  
                 update: "wines",  
                 updates: [  
                    {  
                      q: { variety: "?1" }, u: { $set: { prices: 11 } }, multi: true  
                    }  
                 ],  
                 writeConcern: { w: "majority", wtimeout: 5000 }  
              }',
        percentage: 15,
        params: [
                  {param1: Mavrud},{param1: Ruen},{param1: Cabernet Sauvignon},{param1: Red Blend},{param1: Bordeaux-style Red Blend},{param1: Sauvignon Blanc},{param1: Syrah},{param1: Riesling},{param1: Merlot},{param1: Zinfandel}
                ]
      }  
    - {
        name: updatePricesByProvince ,
        exec: '{  
                 update: "wines",  
                 updates: [  
                    {  
                      q: { province: "?1" }, u: { $set: { prices: 15 } }, multi: true  
                    }  
                 ],  
                 writeConcern: { w: "majority", wtimeout: 5000 }  
              }',
        percentage: 15,
        params: [
                  {param1: Thracian Valley},{param1: Washington},{param1: Tuscany},{param1: Bordeaux},{param1: Northern Spain},{param1: Mendoza Province},{param1: Burgundy},{param1: Piedmont},{param1: Veneto}
                ]
      }
  delete-queries:
    - {
       name: deleteByCountry,
       exec: '{  
                delete: "wines",  
                deletes: [ { q: { country: "?1" }, limit: 0 } ]  
              }',
       params: [
                 {param1: Austria},{param1: France},{param1: Spain}
               ]
      }
    - {
       name: deleteByPoints,
       exec: '{  
                delete: "wines",  
                deletes: [ { q: { points: ?1 }, limit: 0 } ]  
              }',
       params: [
                 {param1: 87},{param1: 88},{param1: 89}
               ]
      }
    - {
       name: deleteByPrice,
       exec: '{  
                delete: "wines",  
                deletes: [ { q: { price: ?1 }, limit: 0 } ]  
              }',
       params: [
                 {param1: 22},{param1: 23},{param1: 24}
               ]
      }