spring:
  profiles: # here is specified the actual DB that should be benchmarked
    active: elasticsearch # elasticsearch,mongodb,cassandra,postgres

logging:
  level:
    root: INFO
    com.akg: INFO

commons:
  input-data-file: src/main/resources/winemag-data_first150k.csv # source file with the data
  batch-size: 5000 # size of records that should be inserted on one pass
  frequency-output-in-ms: 10000 # milliseconds time interval for printing the current result ( for example Inserted Records Per Second until that moment )
  use-cases:
    active-use-case: one # possible values are: one, crud
    # Execution type possible values: 
    #   what: elasticsearch, mongodb 
    #   mode: inserts, search, updates, deletes
    one: {what: elasticsearch, mode: inserts, time-in-ms: 10000}  
    crud:
      - {what: elasticsearch, mode: inserts, time-in-ms: 10000} 
      - {what: elasticsearch, mode: search, time-in-ms: 10000} 
      - {what: elasticsearch, mode: updates, time-in-ms: 10000}
      - {what: elasticsearch, mode: deletes, time-in-ms: 10000}
