spring:
  profiles: 
    active: postgres # elasticsearch,mongodb,cassandra,postgres
 

logging:
  level:
    root: INFO
    com.akg: INFO

commons:
  input-data-file: src/main/resources/winemag-data_first150k.csv
  batch-size: 5000
  frequency-output-in-ms: 10000
  use-cases:
    # possible values are: one, crud
    active-use-case: one
    # Execution type possible values: 
    #   what: elasticsearch, mongodb 
    #   mode: inserts, search, updates, deletes
    one: {what: postgres, mode: inserts, time-in-ms: 60000}  
    crud:
      - {what: postgres, mode: inserts, time-in-ms: 1800000} 
      - {what: postgres, mode: search, time-in-ms: 300000} 
      - {what: postgres, mode: updates, time-in-ms: 60000}
      - {what: postgres, mode: deletes, time-in-ms: 60000}
