commons:
  # mode: inserts, search
  execution: {what: elasticsearch, mode: search} 
  input-data-file: src/main/resources/winemag-data_first150k.csv
  batch-size: 5000
  execution-time-in-ms: 60000

elasticsearch:
  host: localhost
  port: 9200
  protocol: http
  socket-timeout: 10000
  connection-timeout: 5000
  end-point: { search: /wine/_search, insert: /wine/_bulk }
  io-thread-count: 1
  queries:
    - {
       name: queryByCountry,
       data: '{
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                 "match": {
                                                            "country": "?1"
                                                          }
                                               }
                                            ]
                                   }
                         }
              }',
       percentage: 15,
       params: [
                 {param1: Bulgaria},{param1: Romania},{param1: Greece},{param1: Macedonia},{param1: Turkey},{param1: Germany},{param1: France},{param1: Italy},{param1: Austria},{param1: Spain},{param1: Portugal},{param1: Argentina}
               ]
      }
    - {
       name: queryByPoints,
       data: '{
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                  "match": {
                                                             "points": "?1"
                                                           }
                                               }
                                            ]
                                   }
                         }
              }',
       percentage: 15,
       params: [
                 {param1: 91},{param1: 92},{param1: 93},{param1: 94},{param1: 95},{param1: 96},{param1: 97},{param1: 98},{param1: 99},{param1: 100}
               ]
      }
    - {
       name: queryByPrice,
       data: '{
                "query": {
                           "range" : {
                                       "price" : {
                                                   "gte" : ?1
                                                 }
                                     }
                         }
              }',
       percentage: 15,
       params: [
                 {param1: 90},{param1: 91},{param1: 92},{param1: 93},{param1: 94},{param1: 95},{param1: 96},{param1: 97},{param1: 98},{param1: 99},{param1: 100},{param1: 200},{param1: 500},{param1: 1000},{param1: 2000}
               ]
      }
    - {
       name: queryByCountryAndPoints,
       data: '{
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                 "match": {
                                                            "country": "?1"
                                                          }
                                               },
                                               {
                                                  "match": {
                                                             "points": "?2"
                                                           }
                                               }
                                            ]
                                   }
                         }
             }',
       percentage: 25,
       params: [
                 {param1: Bulgaria, param2: 96},{param1: Bulgaria, param2: 97},{param1: Bulgaria, param2: 98},{param1: Bulgaria, param2: 99},{param1: Bulgaria, param2: 100},
                 {param1: Romania,  param2: 96},{param1: Romania, param2: 97},{param1: Romania, param2: 98},{param1: Romania, param2: 99},{param1: Romania, param2: 100},
                 {param1: Greece, param2: 96},{param1: Greece, param2: 97},{param1: Greece, param2: 98},{param1: Greece, param2: 99},{param1: Greece, param2: 100},
                 {param1: Macedonia, param2: 96},{param1: Macedonia, param2: 97},{param1: Macedonia, param2: 98},{param1: Macedonia, param2: 99},{param1: Macedonia, param2: 100},
                 {param1: Turkey, param2: 96},{param1: Turkey, param2: 97},{param1: Turkey, param2: 98},{param1: Turkey, param2: 99},{param1: Turkey, param2: 100},
                 {param1: Germany, param2: 96},{param1: Germany, param2: 97},{param1: Germany, param2: 98},{param1: Germany, param2: 99},{param1: Germany, param2: 100},
                 {param1: France, param2: 96},{param1: France, param2: 97},{param1: France, param2: 98},{param1: France, param2: 99},{param1: France, param2: 100},
                 {param1: Italy, param2: 96},{param1: Italy, param2: 97},{param1: Italy, param2: 98},{param1: Italy, param2: 99},{param1: Italy, param2: 100},
                 {param1: Austria, param2: 96},{param1: Austria, param2: 97},{param1: Austria, param2: 98},{param1: Austria, param2: 99},{param1: Austria, param2: 100},
                 {param1: Spain, param2: 96},{param1: Spain, param2: 97},{param1: Spain, param2: 98},{param1: Spain, param2: 99},{param1: Spain, param2: 100},
                 {param1: Portugal, param2: 96},{param1: Portugal, param2: 97},{param1: Portugal, param2: 98},{param1: Portugal, param2: 99},{param1: Portugal, param2: 100},
                 {param1: Argentina, param2: 96},{param1: Argentina, param2: 97},{param1: Argentina, param2: 98},{param1: Argentina, param2: 99},{param1: Argentina, param2: 100},
                 {param1: Australia, param2: 96},{param1: Australia, param2: 97},{param1: Australia, param2: 98},{param1: Australia, param2: 99},{param1: Australia, param2: 100},
                 {param1: Chile, param2: 96},{param1: Chile, param2: 97},{param1: Chile, param2: 98},{param1: Chile, param2: 99},{param1: Chile, param2: 100},
                 {param1: Serbia, param2: 96},{param1: Serbia, param2: 97},{param1: Serbia, param2: 98},{param1: Serbia, param2: 99},{param1: Serbia, param2: 100}
               ]
      }
    - {
        name: queryAggregations,
        data: '{
	              "size": 0,
                  "aggs": {
	                        "min_price": { "min": { "field": "price" } },
                            "max_price": { "max": { "field": "price" } },
                            "avg_price": { "avg": { "field": "price" } },
                            "rows_count": { "value_count": { "field": "country.keyword"} },
                            "country_count": { "cardinality": { "field": "country.keyword" } }
                          }
               }',
        percentage: 15,
        params: []
      }
    - {
        name: queryCountAndGroupBy,
        data: '{ 
                 "size": 0,
                 "aggs": {
                           "group1": {
                                        "terms": {
                                                  "field": "country.keyword"
                                        },
                                        "aggs": {
                                                 "variety_count": { "cardinality": { "field": "variety.keyword" } }
                                        }
                                     }
                         }
               }',
        percentage: 15,
        params: [
                 {param1: country, param2: points},{param1: country, param2: price},{param1: country, param2: variety},
                 {param1: province, param2: points},{param1: province, param2: variety},{param1: variety, param2: country},
                 {param1: variety, param2: price}
                ]
      }