elasticsearch:
  host: localhost
  port: 9200
  protocol: http
  socket-timeout: 10000
  connection-timeout: 5000
  end-point: { search: /wine/_search, insert: /wine/_bulk, update: /wine/_update/, delete: /wine/_delete_by_query }
  io-thread-count: 1
  search-queries:
    - {
       name: findByCountry,
       exec: '{
                "size": 100,
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                 "match": {
                                                            "country": "?1"
                                                          }
                                               }
                                            ]
                                   }
                         }
              }',
       percentage: 15,
       params: [
                 {param1: Bulgaria},{param1: Romania},{param1: Greece},{param1: Macedonia},{param1: Turkey},{param1: Germany},{param1: France},{param1: Italy},{param1: Austria},{param1: Spain},{param1: Portugal},{param1: Argentina}
               ]
      }
    - {
       name: findByPoints,
       exec: '{
                "size": 100,
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                  "match": {
                                                             "points": "?1"
                                                           }
                                               }
                                            ]
                                   }
                         }
              }',
       percentage: 15,
       params: [
                 {param1: 91},{param1: 92},{param1: 93},{param1: 94},{param1: 95},{param1: 96},{param1: 97},{param1: 98},{param1: 99},{param1: 100}
               ]
      }
    - {
       name: findByPrice,
       exec: '{
                "size": 100,
                "query": {
                           "range" : {
                                       "price" : {
                                                   "gte" : ?1
                                                 }
                                     }
                         }
              }',
       percentage: 15,
       params: [
                 {param1: 90},{param1: 91},{param1: 92},{param1: 93},{param1: 94},{param1: 95},{param1: 96},{param1: 97},{param1: 98},{param1: 99},{param1: 100},{param1: 200},{param1: 500},{param1: 1000},{param1: 2000}
               ]
      }
    - {
       name: findByCountryAndPoints,
       exec: '{
                "size": 100,
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                 "match": {
                                                            "country": "?1"
                                                          }
                                               },
                                               {
                                                  "match": {
                                                             "points": "?2"
                                                           }
                                               }
                                            ]
                                   }
                         }
             }',
       percentage: 25,
       params: [
                 {param1: Bulgaria, param2: 96},{param1: Bulgaria, param2: 97},{param1: Bulgaria, param2: 98},{param1: Bulgaria, param2: 99},{param1: Bulgaria, param2: 100},
                 {param1: Romania,  param2: 96},{param1: Romania, param2: 97},{param1: Romania, param2: 98},{param1: Romania, param2: 99},{param1: Romania, param2: 100},
                 {param1: Greece, param2: 96},{param1: Greece, param2: 97},{param1: Greece, param2: 98},{param1: Greece, param2: 99},{param1: Greece, param2: 100},
                 {param1: Macedonia, param2: 96},{param1: Macedonia, param2: 97},{param1: Macedonia, param2: 98},{param1: Macedonia, param2: 99},{param1: Macedonia, param2: 100},
                 {param1: Turkey, param2: 96},{param1: Turkey, param2: 97},{param1: Turkey, param2: 98},{param1: Turkey, param2: 99},{param1: Turkey, param2: 100},
                 {param1: Germany, param2: 96},{param1: Germany, param2: 97},{param1: Germany, param2: 98},{param1: Germany, param2: 99},{param1: Germany, param2: 100},
                 {param1: France, param2: 96},{param1: France, param2: 97},{param1: France, param2: 98},{param1: France, param2: 99},{param1: France, param2: 100},
                 {param1: Italy, param2: 96},{param1: Italy, param2: 97},{param1: Italy, param2: 98},{param1: Italy, param2: 99},{param1: Italy, param2: 100},
                 {param1: Austria, param2: 96},{param1: Austria, param2: 97},{param1: Austria, param2: 98},{param1: Austria, param2: 99},{param1: Austria, param2: 100},
                 {param1: Spain, param2: 96},{param1: Spain, param2: 97},{param1: Spain, param2: 98},{param1: Spain, param2: 99},{param1: Spain, param2: 100},
                 {param1: Portugal, param2: 96},{param1: Portugal, param2: 97},{param1: Portugal, param2: 98},{param1: Portugal, param2: 99},{param1: Portugal, param2: 100},
                 {param1: Argentina, param2: 96},{param1: Argentina, param2: 97},{param1: Argentina, param2: 98},{param1: Argentina, param2: 99},{param1: Argentina, param2: 100},
                 {param1: Australia, param2: 96},{param1: Australia, param2: 97},{param1: Australia, param2: 98},{param1: Australia, param2: 99},{param1: Australia, param2: 100},
                 {param1: Chile, param2: 96},{param1: Chile, param2: 97},{param1: Chile, param2: 98},{param1: Chile, param2: 99},{param1: Chile, param2: 100},
                 {param1: Serbia, param2: 96},{param1: Serbia, param2: 97},{param1: Serbia, param2: 98},{param1: Serbia, param2: 99},{param1: Serbia, param2: 100}
               ]
      }
    - {
        name: findAggregations,
        exec: '{
                  "size": 0,
                  "aggs": {
                            "min_price": { "min": { "field": "price" } },
                            "max_price": { "max": { "field": "price" } },
                            "avg_price": { "avg": { "field": "price" } },
                            "rows_count": { "value_count": { "field": "country.keyword"} } 
                          }
               }',
       percentage: 15,
       params: []
      }
    - {
        name: findCountAndGroupByCountry,
        exec: '{
                  "size": 0,
                  "aggs": {
                           "group1": {
                                        "terms": {
                                                  "field": "country.keyword",
                                                  "size": 100
                                        },
                                        "aggs": {
                                                 "variety_count": { "cardinality": { "field": "variety.keyword" } }
                                        }
                                     }
                          }
               }',
       percentage: 15,
       params: []
      }
  update-queries:
    - {
        name: updatePointsByCountry,
        exec: '{
                 "script" : {
                 "source": "ctx._source.points = params.points",
                 "lang": "painless",
                 "params" : {
                              "points" : 96
                            }
                 }
        }',
        percentage: 40,
        params: [
                  {param1: Bulgaria},{param1: Romania},{param1: Greece},{param1: Macedonia},{param1: Turkey},{param1: Germany},{param1: France},{param1: Italy},{param1: Austria},{param1: Spain},{param1: Portugal},{param1: Argentina}
                ],
        additional-exec: '{
                "size": 100,
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                 "match": {
                                                            "country": "?1"
                                                          }
                                               }
                                            ]
                                   }
                         }
              }'
      }
    - {
        name: updatePricesByCountry,
        exec: '{
                "script" : {
                "source": "ctx._source.price = params.price",
                "lang": "painless",
                "params" : {
                  "price" : 96
                  }
                }
        }',
        percentage: 15,
        params: [
                  {param1: Bulgaria},{param1: Romania},{param1: Greece},{param1: Macedonia},{param1: Turkey},{param1: Germany},{param1: France},{param1: Italy},{param1: Austria},{param1: Spain},{param1: Portugal},{param1: Argentina}
                ],
        additional-exec: '{
                "size": 100,
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                 "match": {
                                                            "country": "?1"
                                                          }
                                               }
                                            ]
                                   }
                         }
              }'
      }
    - {
        name: updatePointsByVariety,
        exec: '{
                "script" : {
                "source": "ctx._source.points = params.points",
                "lang": "painless",
                "params" : {
                  "points" : 96
                }
              }
        }',
        percentage: 15,
        params: [
                  {param1: Mavrud},{param1: Ruen},{param1: Cabernet Sauvignon},{param1: Red Blend},{param1: Bordeaux-style Red Blend},{param1: Sauvignon Blanc},{param1: Syrah},{param1: Riesling},{param1: Merlot},{param1: Zinfandel}
                ],
        additional-exec: '{
                "size": 100,
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                 "match": {
                                                            "variety": "?1"
                                                          }
                                               }
                                            ]
                                   }
                         }
              }' 
      }
    - {
        name: updatePricesByVariety,
        exec: '{
                "script" : {
                "source": "ctx._source.price = params.price",
                "lang": "painless",
                "params" : {
                  "price" : 96
                }
              }
        }',
        percentage: 15,
        params: [
                  {param1: Mavrud},{param1: Ruen},{param1: Cabernet Sauvignon},{param1: Red Blend},{param1: Bordeaux-style Red Blend},{param1: Sauvignon Blanc},{param1: Syrah},{param1: Riesling},{param1: Merlot},{param1: Zinfandel}
                ],
        additional-exec: '{
                "size": 100,
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                 "match": {
                                                            "variety": "?1"
                                                          }
                                               }
                                            ]
                                   }
                         }
              }'
      }  
    - {
        name: updatePricesByProvince ,
        exec: '{
                "script" : {
                "source": "ctx._source.price = params.price",
                "lang": "painless",
                "params" : {
                  "price" : 96
                }
              }
        }',
        percentage: 15,
        params: [
                  {param1: Thracian Valley},{param1: Washington},{param1: Tuscany},{param1: Bordeaux},{param1: Northern Spain},{param1: Mendoza Province},{param1: Burgundy},{param1: Piedmont},{param1: Veneto}
                ],
        additional-exec: '{
                "size": 100,
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                 "match": {
                                                            "province": "?1"
                                                          }
                                               }
                                            ]
                                   }
                         }
              }'
      }
  delete-queries:
    - {
       name: deleteByCountry,
       exec: '{
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                 "match": {
                                                            "country": "?1"
                                                          }
                                               }
                                            ]
                                   }
                         }
              }',
       params: [
                 {param1: Italy},{param1: Slovenia},{param1: Serbia}
               ]
      }
    - {
       name: deleteByPoints,
       exec: '{
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                  "match": {
                                                             "points": ?1
                                                           }
                                               }
                                            ]
                                   }
                         }
              }',
       params: [
                 {param1: 84},{param1: 85},{param1: 86}
               ]
      }
    - {
       name: deleteByPrice,
       exec: '{
                "query": {
                           "bool": {
                                     "must": [
                                               {
                                                  "match": {
                                                             "price": ?1
                                                           }
                                               }
                                            ]
                                   }
                         }
              }',
       params: [
                 {param1: 15},{param1: 16},{param1: 17}
               ]
      }