spring:
  profiles:
    include: elasticsearch,mongodb

logging:
  level:
    root: INFO
    com.akg: INFO

commons:
  input-data-file: src/main/resources/winemag-data_first150k.csv
  batch-size: 5000
  frequency-output-in-ms: 10000
  use-cases:
    active-use-case: one # possible values are one, crud
    one: {what: elasticsearch, mode: search, time-in-ms: 60000}  # Execution type possible values: what: elasticsearch, mongodb | mode: inserts, search, updates, deletes
    crud:
      - {what: mongodb, mode: inserts, time-in-ms: 1800000} 
      - {what: mongodb, mode: search, time-in-ms: 300000} 
      - {what: mongodb, mode: updates, time-in-ms: 60000}
      - {what: mongodb, mode: deletes, time-in-ms: 60000}
