spring:
  profiles:
    include: elasticsearch

commons:
  # mode: inserts, search, updates, deletes
  execution: {what: elasticsearch, mode: deletes} 
  input-data-file: src/main/resources/winemag-data_first150k.csv
  batch-size: 5000
  execution-time-in-ms: 60000

logging:
  level:
    root: INFO
    com.akg: DEBUG
    